apiVersion: v1
kind: ConfigMap

metadata:
  name: "{{ include "image-server.name" . }}"

data:

  # FIXME REDESIGN FULLY - LEGACY ONLY !!!

  MCA_FORCE_STRICT_DATA_SOURCE_AVAILABILITY_CHECK: {{ .Values.imageserver.dbSettings.mcaForceStrictDataSourceAvailabilityCheck | quote }}

  JAVA_AGENT_PORT: {{ .Values.service.metrics.port | quote }}

  MCA_AS_MAIN_DATA_SOURCE_SSL_REQUIRED: {{ .Values.imageserver.dbSettings.main.mcaMainDataSourceSslRequired | quote }}
  MCA_AS_MAIN_DATA_SOURCE_CONNECTION_TIMEOUT: {{ .Values.imageserver.dbSettings.main.connectionTimeout | quote }}
  MCA_AS_MAIN_DATA_SOURCE_CONNECTION_VALIDATION_TIMEOUT: {{ .Values.imageserver.dbSettings.main.connectionValidationTimeout | quote }}
  MCA_AS_MAIN_DATA_SOURCE_MIN_POOL_SIZE: {{ .Values.imageserver.dbSettings.main.minPoolSize | quote }}
  MCA_AS_MAIN_DATA_SOURCE_MAX_POOL_SIZE: {{ .Values.imageserver.dbSettings.main.maxPoolSize | quote }}

  MCA_IMAGE_DATA_SOURCE_SSL_REQUIRED: {{ .Values.imageserver.dbSettings.image.mcaImageDataSourceSslRequired | quote }}
  MCA_IMAGE_DATA_SOURCE_CONNECTION_TIMEOUT: {{ .Values.imageserver.dbSettings.image.connectionTimeout | quote }}
  MCA_IMAGE_DATA_SOURCE_CONNECTION_VALIDATION_TIMEOUT: {{ .Values.imageserver.dbSettings.image.connectionValidationTimeout | quote }}
  MCA_IMAGE_DATA_SOURCE_MIN_POOL_SIZE: {{ .Values.imageserver.dbSettings.image.minPoolSize | quote }}
  MCA_IMAGE_DATA_SOURCE_MAX_POOL_SIZE: {{ .Values.imageserver.dbSettings.image.maxPoolSize | quote }}

  MCA_MH_DATA_SOURCE_SSL_REQUIRED: {{ .Values.imageserver.dbSettings.mh.mcaMhDataSourceSslRequired | quote }}
  MCA_MH_DATA_SOURCE_CONNECTION_TIMEOUT: {{ .Values.imageserver.dbSettings.mh.connectionTimeout | quote }}
  MCA_MH_DATA_SOURCE_CONNECTION_VALIDATION_TIMEOUT: {{ .Values.imageserver.dbSettings.mh.connectionValidationTimeout | quote }}
  MCA_MH_DATA_SOURCE_MIN_POOL_SIZE: {{ .Values.imageserver.dbSettings.mh.minPoolSize | quote }}
  MCA_MH_DATA_SOURCE_MAX_POOL_SIZE: {{ .Values.imageserver.dbSettings.mh.maxPoolSize | quote }}
