apiVersion: v1
kind: Secret

metadata:
  name: "{{ include "image-server.name" . }}"

data:

  MCA_IMAGE_ADMIN_USER_NAME: {{ .Values.imageserver.adminSettings.user | b64enc | quote }}
  MCA_IMAGE_ADMIN_USER_PASSWORD_HASH: {{ .Values.imageserver.adminSettings.passwordHash | b64enc | quote }}
