apiVersion: v1
kind: Service
metadata:
  name: {{ include "image-server.name" . }}
  labels:
    app: {{ include "image-server.name" . }}
    chart: {{ include "image-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.metrics.port }}
      targetPort: metrics
      protocol: TCP
      name: metrics

  selector:
    app: {{ include "image-server.name" . }}
    release: {{ .Release.Name }}
